// Tier K — Drift across versions.
//
// Verifies that manifests from older versions round-trip through the
// current pipeline without data loss. Catches the case where a schema
// change in version N+1 silently breaks regenerate of projects
// generated by version N.
//
// In-process subset of the full version-drift suite. The shell-script
// version (`tests/e2e/drift-across.sh`) installs actual npm versions
// 0.1.40, 0.1.41 etc. and round-trips a real project — that's slower
// and runs pre-release. This file exercises the mechanism with
// hand-crafted fixture manifests that mimic each historical shape.
//
// See docs/TEST-PLAN.md Tier K.

import { describe, it, expect } from "vitest";
import { parse as yamlParse, stringify as yamlStringify } from "yaml";
import { mkdtempSync, rmSync, writeFileSync, readFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import { execSync } from "child_process";

const REPO = "/srv/repos/Abax-Swarm";
const CLI_TSX = `node --import tsx ${REPO}/src/cli/app.ts`;

// 0.1.40-shape manifest — pre-policy-override fields, no
// active_iteration_scope. Our 0.1.42 pipeline should accept this and
// produce a valid project without losing the user's intent.
const MANIFEST_0_1_40_SHAPE = `
project:
  name: drift-test
  description: 0.1.40-shape manifest fixture
  size: small
  stack: angular-quarkus
  target: opencode
  team_scope: full
  provider: anthropic
  model_strategy: inherit
  permission_mode: recommended
  isolation_mode: host
  governance_model: lightweight
  governance_name: Equipo Ligero
team:
  total_agents: 9
  roles: []
skills: []
tools: []
criteria_applied: []
warnings: []
generated_at: '2026-05-01T00:00:00.000Z'
generated_by: abax-swarm v0.1.40
`;

// 0.1.41-shape manifest — adds policy override blocks (commented or
// active). Should also round-trip cleanly through 0.1.42.
const MANIFEST_0_1_41_SHAPE = `${MANIFEST_0_1_40_SHAPE}

# ============================================================================
# Optional policy overrides (v0.1.40+)
# ============================================================================

# task_contracts_override:
#   forbidden_combinations:
#     - id: my-rule
#       actions: [build, deploy]
#       reason: example
`;

// 0.1.42-shape — unchanged from 0.1.41 (no schema change)
const MANIFEST_0_1_42_SHAPE = MANIFEST_0_1_41_SHAPE;

describe("Tier K — Drift across versions (in-process)", () => {
  function regenerateFromManifest(manifestYaml: string): {
    dir: string;
    cleanup: () => void;
    stdout: string;
    stderr: string;
    success: boolean;
  } {
    const dir = mkdtempSync(join(tmpdir(), "abax-drift-"));
    writeFileSync(join(dir, "project-manifest.yaml"), manifestYaml);
    let stdout = "";
    let stderr = "";
    let success = false;
    try {
      stdout = execSync(`${CLI_TSX} regenerate --dir ${dir}`, {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
        cwd: REPO,
      });
      success = true;
    } catch (e: unknown) {
      const err = e as { stdout?: Buffer; stderr?: Buffer; status?: number };
      stdout = err.stdout?.toString() ?? "";
      stderr = err.stderr?.toString() ?? "";
      success = false;
    }
    return {
      dir,
      stdout,
      stderr,
      success,
      cleanup: () => rmSync(dir, { recursive: true, force: true }),
    };
  }

  it("0.1.40-shape manifest regenerates successfully under 0.1.42 schema", () => {
    const result = regenerateFromManifest(MANIFEST_0_1_40_SHAPE);
    try {
      expect(result.success, `regenerate failed: ${result.stderr}`).toBe(true);
      expect(result.stdout).toMatch(/Proyecto generado exitosamente/);
    } finally {
      result.cleanup();
    }
  });

  it("0.1.41-shape manifest (commented overrides) regenerates successfully", () => {
    const result = regenerateFromManifest(MANIFEST_0_1_41_SHAPE);
    try {
      expect(result.success, `regenerate failed: ${result.stderr}`).toBe(true);
    } finally {
      result.cleanup();
    }
  });

  it("regenerated manifest preserves user-set overrides (round-trip preservation)", () => {
    const userManifest = MANIFEST_0_1_40_SHAPE + `
task_contracts_override:
  forbidden_combinations:
    - id: my-custom-rule
      actions:
        - build
        - deploy
      reason: User-specific guardrail
`;
    const result = regenerateFromManifest(userManifest);
    try {
      expect(result.success).toBe(true);
      const newManifestPath = join(result.dir, "project-manifest.yaml");
      const newManifest = readFileSync(newManifestPath, "utf8");
      // The user's override block must be preserved
      expect(newManifest).toContain("my-custom-rule");
      expect(newManifest).toContain("User-specific guardrail");
      // Active overrides header should appear
      expect(newManifest).toMatch(/Active policy overrides/);
    } finally {
      result.cleanup();
    }
  });

  it("regenerated manifest preserves active_iteration_scope when set", () => {
    const userManifest = MANIFEST_0_1_40_SHAPE + `
active_iteration_scope: minor
`;
    const result = regenerateFromManifest(userManifest);
    try {
      expect(result.success).toBe(true);
      const newManifest = readFileSync(join(result.dir, "project-manifest.yaml"), "utf8");
      expect(newManifest).toMatch(/active_iteration_scope:\s*minor/);
    } finally {
      result.cleanup();
    }
  });

  it("regenerate produces valid policies.json under current schema", () => {
    const result = regenerateFromManifest(MANIFEST_0_1_40_SHAPE);
    try {
      expect(result.success).toBe(true);
      const policiesPath = join(result.dir, ".opencode/policies/abax-policies.json");
      const policiesJson = JSON.parse(readFileSync(policiesPath, "utf8"));
      // Spot-check current-schema fields
      expect(policiesJson).toHaveProperty("phases");
      expect(policiesJson).toHaveProperty("role_categories");
      expect(policiesJson).toHaveProperty("task_contracts");
      expect(Array.isArray(policiesJson.phases)).toBe(true);
      expect(policiesJson.phases.length).toBeGreaterThan(0);
    } finally {
      result.cleanup();
    }
  });

  it("regenerate keeps generated_by version current (not stuck on old version)", () => {
    const result = regenerateFromManifest(MANIFEST_0_1_40_SHAPE);
    try {
      expect(result.success).toBe(true);
      const newManifest = readFileSync(join(result.dir, "project-manifest.yaml"), "utf8");
      const parsed = yamlParse(newManifest) as { generated_by?: string };
      expect(parsed.generated_by ?? "").not.toContain("0.1.40");
      expect(parsed.generated_by ?? "").not.toContain("0.1.39");
    } finally {
      result.cleanup();
    }
  });
});
